FROM microsoft/dotnet:2.0-sdk

RUN git clone https://<token>:x-oauth-basic@github.com/Innovassu/Yuffie.git /app

WORKDIR /app/WebApp

RUN export ASPNETCORE_ENVIRONMENT=Development

RUN dotnet restore
RUN dotnet publish -c Release -o out


ENTRYPOINT ["dotnet", "run"]
