version: '2'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile-yuff
    links:
      - database
    ports:
      - 80:8080
    tty: true

  database:
    # build:
    #   context: .
    #   dockerfile: Dockerfile-neo4j
    image: neo4j:latest
    volumes:
      - /data:/data
    ports:
      - 7474:7474
      - 7689:7687
    environment:
      - NEO4J_AUTH=none

